[package]
name = "ironwork"
description = "ironwork for COBOL: the compiler driver"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
exec = { package = "ironwork-exec", path = "../exec", version = "0.2.0" }
jcl = { package = "ironwork-jcl", path = "../jcl", version = "0.2.0" }
numeric = { package = "ironwork-numeric", path = "../numeric", version = "0.2.0" }
rt = { package = "ironwork-rt", path = "../rt", version = "0.2.0" }
syntax = { package = "ironwork-syntax", path = "../syntax", version = "0.2.0" }
zarch = { package = "ironwork-zarch", path = "../zarch", version = "0.2.0" }

[lints]
workspace = true
