[package]
name = "ironwork-jcl"
description = "ironwork for COBOL: a reader for z/OS job control language"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
syntax = { package = "ironwork-syntax", path = "../syntax", version = "=0.8.0" }

[lints]
workspace = true
