DROP TABLE asg;
DROP TABLE emp;
CREATE TABLE emp (id INTEGER NOT NULL PRIMARY KEY, name CHAR(10) NOT NULL, amt DECIMAL(7,2), note VARCHAR(20), stamp TIMESTAMP, t TIME);
CREATE TABLE asg (emp INTEGER NOT NULL, FOREIGN KEY (emp) REFERENCES emp (id));
INSERT INTO emp VALUES (1, 'ADAMS', 100.50, 'A LONGER NOTE TEXT', '2020-01-02-03.04.05.500000', '13.45.06'), (2, 'BAKER', NULL, NULL, NULL, NULL), (3, 'CLARK', 30, 'SHORT', NULL, NULL);
